{% set name = "url-normalize" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d23d3a070ac52a67b83a1c59a0e68f8608d1cd538783b401bc9de2c0fac999b2
  patches:
    - patches/0001-change-build-backend-to-poetry-core.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  build:
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - python
    - pip
    - poetry-core
    - setuptools
    - wheel
  run:
    - python
    - six

test:
  imports:
    - url_normalize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/niksite/url-normalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: URL normalization for Python
  description: |
    URL normalization for Python.
    Normalizes encoding, schemes, hosts, ports, IDN domains, authorities, and other URL variations.
  doc_url: https://github.com/niksite/url-normalize
  dev_url: https://github.com/niksite/url-normalize

extra:
  recipe-maintainers:
    - jwcook
